sudo: required
dist: trusty
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
language: node_js
node_js:
- '4'
- '5'
- '6'
- node
matrix:
  fast_finish: true
  allow_failures:
  - node_js: '4'
install:
- npm install
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- npm run lint
- npm test
- npm run build:prod
- npm run server:prod:ci &
- sleep 3
- npm run e2e
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: NG08ixOjGr1T2RNgnVe1NthctPVroQOIZALLw+bL+E+5eYvzo0d4RvTMS0zDcy5tvBVG7ANrFHMNth4S870EztXtLPEn1aA/BIHqwrXV70QsTv4HbwcG68oA4Two5CpqnZd6sjbBVlZ7cJaGKSv5H+IllsstCIHYIG1u+3S1zt9TmaLoY/0saGtrR8ZmewW0nUHufYTzDZtRAi4UggSoIUap8HgZ+2DWZU9TEGDbWqENHmMnbTJWVPiEG09lXeDrRQom9RTSEZPp0K0n1Atsx1G8khzuN1lGyXTp42ci/hcJkXYKEnrmoW7nfqqKOxj6wRVnUbtFNCE35iAYK1NzNCJU+pjXyN6uwY6RuPHr9U3L4Gp+GZT2FN5jU+cBbOkudfRmAMq4U6JzP3JC3UjgOHEV9S2cF260qScOpFMEavDYdfF7K24Dpgy9GpOOKf2A+hsGeoK8pG0GiBtR3odh8r4s3iwIjzPBkqUCvcnDVyon9svWsyUmCsfrpxHmpEjZphU1laJPSfnOYJ61+hvO9f64qWWHpoeKcUrJOKbByOIfd9RnAxrVp8AFPnwOaVtkd4GXRF4SG7t5dOFpTmLd2TybGBY866vqaIrLw3JT2uwgMkg+bDC5Amgi+VIhhX6tkeNJt3japSmxxVYEPdnt9jdsCQMSIM9OkDNYugf/Lj4=
